import streamlit as st
import tensorflow as tf
import numpy as np
from PIL import Image
import io
from fpdf import FPDF
import os

# ---------------- PAGE CONFIG ----------------
st.set_page_config(
    page_title="Skin Cancer Detection Dashboard",
    layout="wide"
)

# ---------------- CUSTOM CSS ----------------
st.markdown("""
<style>
.stApp {
    background: linear-gradient(135deg, #ede7ff, #f6f3ff);
}

/* Sidebar */
section[data-testid="stSidebar"] {
    background: linear-gradient(180deg, #e6dcff, #f3edff);
}

/* Card */
.card {
    background: rgba(255,255,255,0.8);
    backdrop-filter: blur(12px);
    border-radius: 18px;
    padding: 22px;
    margin-bottom: 20px;
    box-shadow: 0 12px 30px rgba(0,0,0,0.08);
}

/* Upload box */
div[data-testid="stFileUploader"] > div {
    background-color: #f4f1ff;
    border-radius: 14px;
}

/* Browse files button */
button[kind="secondary"] {
    background: linear-gradient(135deg, #7b5cff, #9a7cff) !important;
    color: white !important;
    border-radius: 12px !important;
    font-weight: 600 !important;
}

/* PDF download button */
div[data-testid="stDownloadButton"] button {
    background: linear-gradient(135deg, #7b5cff, #9a7cff) !important;
    color: white !important;
    border-radius: 12px !important;
    font-weight: 600 !important;
}

/* Progress bar */
div[data-testid="stProgress"] > div > div {
    background: linear-gradient(90deg, #7b5cff, #9a7cff);
}
</style>
""", unsafe_allow_html=True)

# ---------------- LOAD MODEL ----------------
@st.cache_resource
def load_model():
    if not os.path.exists("skin_cancer_model.h5"):
        st.error("❌ skin_cancer_model.h5 not found")
        st.stop()
    return tf.keras.models.load_model("skin_cancer_model.h5")

model = load_model()

# ---------------- SIDEBAR ----------------
st.sidebar.markdown("## 📊 Dashboard Info")
st.sidebar.write(
    "AI-based skin cancer detection using a CNN model trained on dermoscopic images."
)
show_metrics = st.sidebar.checkbox("Show Training Metrics", value=True)

# ---------------- HEADER ----------------
st.markdown("""
<div class="card" style="text-align:center;">
    <h1>🧬 Skin Cancer Detection Dashboard</h1>
    <p>AI-powered classification of skin lesions (Benign vs Malignant)</p>
</div>
""", unsafe_allow_html=True)

# ---------------- FILE UPLOAD ----------------
st.markdown('<div class="card">', unsafe_allow_html=True)
st.subheader("📤 Upload Skin Lesion Image (JPG, JPEG, PNG)")

uploaded_file = st.file_uploader(
    "Drag and drop file here",
    type=["jpg", "jpeg", "png"]
)
st.markdown('</div>', unsafe_allow_html=True)

# ---------------- IMAGE PREPROCESS ----------------
def preprocess_image(img):
    img = img.resize((224, 224))
    img = np.array(img) / 255.0
    return np.expand_dims(img, axis=0)

label = None
confidence_percent = None

# ---------------- PREDICTION ----------------
if uploaded_file:
    image = Image.open(uploaded_file).convert("RGB")

    st.markdown('<div class="card">', unsafe_allow_html=True)
    st.image(image, caption="Uploaded Image", width=260)
    st.markdown('</div>', unsafe_allow_html=True)

    input_img = preprocess_image(image)
    prediction = model.predict(input_img)[0][0]  # malignant probability

    # ✅ FIXED CONFIDENCE LOGIC
    if prediction < 0.5:
        label = "Benign (Non-cancerous)"
        confidence_percent = (1 - prediction) * 100
        st.success(f"✅ Prediction: {label}")
    else:
        label = "Malignant (Cancerous)"
        confidence_percent = prediction * 100
        st.error(f"⚠️ Prediction: {label}")

    st.write(f"**Confidence:** {confidence_percent:.2f}%")
    st.progress(int(confidence_percent))

# ---------------- PDF REPORT ----------------
def generate_pdf(label, confidence):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", size=12)

    pdf.cell(0, 10, "Skin Cancer Detection Report", ln=True)
    pdf.ln(6)
    pdf.cell(0, 10, f"Prediction: {label}", ln=True)
    pdf.cell(0, 10, f"Confidence: {confidence:.2f}%", ln=True)
    pdf.ln(6)
    pdf.multi_cell(
        0, 10,
        "Disclaimer: This result is generated by an AI model and is for educational purposes only."
    )

    buffer = io.BytesIO()
    pdf.output(buffer)
    buffer.seek(0)
    return buffer

if uploaded_file and label:
    pdf_data = generate_pdf(label, confidence_percent)

    st.markdown('<div class="card">', unsafe_allow_html=True)
    st.download_button(
        label="📄 Download PDF Report",
        data=pdf_data,
        file_name="skin_cancer_report.pdf",
        mime="application/pdf"
    )
    st.markdown('</div>', unsafe_allow_html=True)

# ---------------- TRAINING METRICS ----------------
if show_metrics and os.path.exists("training_curves.png"):
    st.markdown('<div class="card">', unsafe_allow_html=True)
    st.subheader("📈 Model Training Insights")
    st.image("training_curves.png", use_column_width=True)
    st.markdown('</div>', unsafe_allow_html=True)

# ---------------- FOOTER ----------------
st.markdown("""
<p style="text-align:center; opacity:0.7;">
⚠️ Educational use only – Not a medical diagnosis<br>
Developed using TensorFlow & Streamlit
</p>
""", unsafe_allow_html=True)
